# version: '3.8'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: jobsphere-app
    restart: unless-stopped
    ports:
      - "${PORT:-4000}:4000"
    environment:
      NODE_ENV: production
      TZ: Asia/Dhaka
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
      API_BASE_URL: ${API_BASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
